<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
	
	<bean id="dataSource" class="org.springframework.jdbc.datasource.SimpleDriverDataSource">
		<property name="driverClass" value="com.mysql.jdbc.Driver" />
		<property name="url" value="jdbc:mysql://localhost/springbook" />
		<property name="username" value="spring" />
		<property name="password" value="book" />
	</bean>
	
	<!-- 새로운 jdbcContext를 bean으로 등록 -->
	<!-- 
		수동 DI를 위해 bean에서 제거
	<bean id="jdbcContext" class="me.dec7.user.dao.JdbcContext">
		<property name="dataSource" ref="dataSource" />
	</bean>
	-->
	
	<bean id="userDao" class="me.dec7.user.dao.UserDao">
		<property name="dataSource" ref="dataSource" />
		
		<!-- bean 의존관계 변경 -->
		<!-- 
		수동 DI를 위해 bean에서 제거
		<property name="jdbcContext" ref="jdbcContext" />
		-->
	</bean>
	
	<!-- p303, oracle 에러코드 맵핑 파일 
	맵핑되는 예외는 모두 DataAccessException의 subtype
	
	<bean id="Oracle" class="org.springframework.jdbc.support.SQLErrorCodes">
		<property name="badSqlGrammerCodes">
			<value>900,903,904,917,936,942,10076</value>
		</property>
		<property name="invalidResultSetAccessCodes">
			<value>17003</value>
		</property>
		<property name="duplicateKeyCodes">
			<value>1</value>
		</property>
		<property name="dataIntegrityViolationCodes">
			<value>1400,1722,2291,2292</value>
		</property>
		<property name="dataAccessResourceFailureCodes">
			<value>17002,17447</value>
		</property>
	</bean>
	-->
	
	
	


</beans>
